import Head from "next/head";
import { useState, useEffect } from "react";
import { useRouter } from "next/router";

const mainURL = "http://127.0.0.1:4000/";

const Home = () => {
  const [roomId, setRoomId] = useState("");
  const [playerId, setPlayerId] = useState<String | null>(null);
  const router = useRouter();

  useEffect(() => {
    const id = localStorage.getItem("playerId");
    if (id) {
      setPlayerId(id);
    } else {
      fetchPlayerId();
    }
  }, []);

  const fetchPlayerId = async () => {
    try {
      const response = await fetch(mainURL + "playerId");
      const data = await response.json();
      const id = await data.playerId;
      setPlayerId(id);
      localStorage.setItem("playerId", id);
    } catch (error) {
      //TODO: better error handling
      console.log(error);
    }
  };

  const handleCreateGame = async () => {
    try {
      const response = await fetch(mainURL + "game/create", {
        method: "POST",
        body: JSON.stringify(playerId),
      });

      const data = await response.json();
      const roomId = await data.roomId;
      console.log(roomId);
      router.push(`/game/${roomId}`);
    } catch (error) {
      console.log(error);
    }
  };

  const handleJoinRoom = () => {
    router.push(`/game/${gameId}`);
  };

  const handleRoomIdChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setRoomId(event.target.value);
  };

  return (
    <>
      <Head>
        <title>TicTacToe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Tic Tac Toe</h1>
        <button onClick={handleCreateGame}>Create Room</button>
        <div>
          <label htmlFor="game-id">Room ID:</label>
          <input
            type="text"
            id="game-id"
            value={roomId}
            onChange={handleRoomIdChange}
          />
          <button onClick={handleJoinRoom}>Join Room</button>
        </div>
      </div>
    </>
  );
};

export default Home;
